language: node_js
node_js:
    - "8.11"
branches:
  only:
  - master

before_script:
    - npm install -g @angular/cli
    - cd src/app
script:
    - ng build --prod --base-href https://prajwal88.github.io/sunbird-style-guide/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master